### ISSUE TITLE
cache breaks with large fits

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#101]
sqlite3 has a maximum row size of 2GB. This means we cannot save fits in the sqlite3 cache because people will fit models with enormous numbers of parameters or, more likely, an enormous number of draws. Switching to leveldb or something even simpler might solve the issue.

**Comment by ahartikainen** [comment]
Is this true? Some sources say it is 140TB

https://stackoverflow.com/questions/14451624/will-sqlite-performance-degrade-if-the-database-size-is-greater-than-2-gigabytes

**Comment by riddell-stan** [comment]
Fixed in https://github.com/stan-dev/httpstan/commit/5edc089dd6998a36d38088da4b44aa0a3337e75a
