### ISSUE TITLE
httpstan is slow with small fits (benchmarks)

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#102]
The benchmark here is 8 schools but with varying `J` to make things slow enough
that we can make measurements: 800 schools and 8000 schools. (The remaining
data is simply repeated the appropriate number of times.) In both cases the
models are compiled with `-DSTAN_THREADS`. Here are the results:

| J     | thin | cmdstan 2.18 | httpstan 0.6.1 | % slower |
| ----- | ---  | ------- | ---      | ---      |
| 800   | 1    |  4.5s   | 17s      | 270%     |  
| 8000  | 50   |  1m31s  | 1m45s    | 15%      |

TODO: add cmdstan without ``-DSTAN_THREADS``

Encoding things into protobuf format is the bottleneck. Since draws are coming out of Stan C++
much slower in the J = 8000 case, the bottleneck goes away. Two things would improve things, I suspect:

- Moving the protobuf encoding into Cython/C++. If the protobuf_writer emerges (/cc @sakrejda), this would solve the problem.
- Writing Stan C++ output to disk or to a cache in Cython rather than via the `async for` loop. Python loops are slow.

I'm happy with the progress so far. Things were far slower a week ago.

**Comment by sakrejda** [comment]
I did implement protobuf-based writers, with tests and all.  You didn't like the schema I used and wanted to implement your own.  Without agreement across interfaces there wasn't much reason to put them into CmdStan.  ¯\_(ツ)_/¯  I'm pretty sure the patterns in my fork of CmdStan are applicable for use with other schema if you wanted to modify them to work with your own schema.

**Comment by riddell-stan** [comment]
OK. I'll have a look at your fork. Maybe we can figure some compromise 
between my schema and yours.

**Comment by ahartikainen** [comment]
Can we use some fast compression library (lz4 / blosc) to compress data "on-the-fly" and then encode smaller amount of data?

**Comment by bob-carpenter** [comment]
How widely available are those systems?  We need something on the fast side.  How about simple `bzip2`, which now seems to be included with zip.  We don't want someone to create output and then have a hassle being able to uncompress it.

**Comment by ahartikainen** [comment]
Blosc is probably harder one, lz4 is easier to install.

gzip is also fast.

Also, are we going to compress large or small data (chunks)? That should affect what is the best option (time + size).

**Comment by riddell-stan** [comment]
Yes, we'll do something like that. Right now models (but not fits) are gzip compressed. I'm not going to worry about this until we get closer to ~100% as fast/slow as PyStan 2.

**Comment by riddell-stan** [comment]
Just tried a wonderful sampling profiler, [py-spy](https://github.com/benfred/py-spy). The parsing of the JSON-based encoding of the Stan messages is definitely where we should focus our attention:
```
100.00% 100.00%   13.28s    13.28s   readinto (/usr/lib/python3.6/socket.py:586)
 31.00%  31.00%    4.11s     4.11s   call (/home/fest/work/stan/httpstan/httpstan/services_stub.py:85)
 18.00%  69.00%    2.26s     8.85s   call (/home/fest/work/stan/httpstan/httpstan/services_stub.py:78)
 13.00%  13.00%    1.73s     1.73s   parse_diagnostic_writer (/home/fest/work/stan/httpstan/httpstan/callbacks_writer_parser.py:132)
 10.00%  10.00%    1.22s     1.22s   parse_diagnostic_writer (/home/fest/work/stan/httpstan/httpstan/callbacks_writer_parser.py:131)
  9.00%   9.00%    1.23s     1.23s   parse_sample_writer (/home/fest/work/stan/httpstan/httpstan/callbacks_writer_parser.py:115)
  5.00%   5.00%   0.550s    0.550s   parse_sample_writer (/home/fest/work/stan/httpstan/httpstan/callbacks_writer_parser.py:113)
  4.00%   4.00%   0.230s    0.230s   parse (/home/fest/work/stan/httpstan/httpstan/callbacks_writer_parser.py:72)
  4.00%   4.00%   0.710s    0.710s   parse_sample_writer (/home/fest/work/stan/httpstan/httpstan/callbacks_writer_parser.py:114)
  3.00%   3.00%   0.620s    0.620s   parse_diagnostic_writer (/home/fest/work/stan/httpstan/httpstan/callbacks_writer_parser.py:130)
  2.00%   2.00%   0.160s    0.160s   parse_diagnostic_writer (/home/fest/work/stan/httpstan/httpstan/callbacks_writer_parser.py:129)
  1.00%   1.00%   0.080s    0.080s   parse_sample_writer (/home/fest/work/stan/httpstan/httpstan/callbacks_writer_parser.py:112)
  0.00%   0.00%   0.000s    0.010s   <module> (aiohttp/http_websocket.py:77)
  0.00%   0.00%   0.000s    0.010s   __init__ (/usr/lib/python3.6/subprocess.py:709)
  0.00%   0.00%   0.020s    0.020s   encode (os.py:743)
```

**Comment by ahartikainen** [comment]
Is that json thing called multiple times or once?

**Comment by riddell-stan** [comment]
`json` is being used all the time. It's here: https://github.com/stan-dev/httpstan/blob/master/httpstan/callbacks_writer_parser.py

Every time a callback_writer writes something it gets converted to a JSON string and then decoded in the callbacks_writer_parser.py. I think the way to fix this is to use protcolbuffers earlier. This means including the protobuf library with httpstan so we can use it in ``https://github.com/stan-dev/httpstan/blob/master/httpstan/queue_writer.hpp``. I used protobuf in C++ before so that's why there's a delay.

**Comment by riddell-stan** [comment]
I just stumbled upon this. It's a Python protobuf library written in Cython which claims to be much faster than Google's Python implementation: https://github.com/appnexus/pyrobuf

**Comment by wds15** [comment]
Another benchmark you could consider to look at is the SIR example in the cmdstan performance repository created by @seantalts. In case the slowdown is mostly due to the current develop `STAN_THREADS` implementation, then the SIR example will reveal that nicely. Should this be your performance critical blocker, then the new PR which changes the `STAN_THREADS` implementation to run fast now does resolve your performance problems.

**Comment by ahartikainen** [comment]
Are we sending everything (samples) in one group or is httpstan yielding samples constantly?

**Comment by riddell-stan** [comment]
httpstan is sending samples constantly, as they arrive.

**Comment by riddell-stan** [comment]
Moved the writing of protobuf messages over to C++. 6x speedup.

Now we need to figure out how to build and distribute `libprotobuf-lite.so`. Currently my setup requires having protobuf installed as a system library.

**Comment by ahartikainen** [comment]
Can we pack it with wheel?

**Comment by riddell-stan** [comment]
I hope so. That's definitely the goal.

**Comment by ahartikainen** [comment]
This might be interesting solution

https://stackoverflow.com/questions/23916186/how-to-include-external-library-with-python-wheel-package

Not sure if there are some other ways to handle this

**Comment by riddell-stan** [comment]
That looks remarkably easy! I was afraid we were going to have to change 
build systems entirely.
