### ISSUE TITLE
Can not install pip / clone

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/httpstan#11]
Can not install with pip for new conda-env on macosx El Capitan.

C++ compiler Xcode: Apple LLVM version 8.0.0 (clang-800.0.42.1)

    conda create -n httpstan_env python=3.6
    source activate httpstan_env

# Pip fails

    pip install httpstan

the error message.

    g++ -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/ahartikainen/miniconda2/envs/httpstan_env/lib -L/Users/ahartikainen/miniconda2/envs/httpstan_env/lib -headerpad_max_install_names -Wl,-rpath,/Users/ahartikainen/miniconda2/envs/httpstan_env/lib -L/Users/ahartikainen/miniconda2/envs/httpstan_env/lib -headerpad_max_install_names -arch x86_64 build/temp.macosx-10.9-x86_64-3.6/httpstan/stan.o -L/Users/ahartikainen/miniconda2/envs/httpstan_env/lib -o build/lib.macosx-10.9-x86_64-3.6/httpstan/stan.cpython-36m-darwin.so
        building 'httpstan.compile' extension
        creating build/temp.macosx-10.9-x86_64-3.6/httpstan/lib
        creating build/temp.macosx-10.9-x86_64-3.6/httpstan/lib/stan
        creating build/temp.macosx-10.9-x86_64-3.6/httpstan/lib/stan/src
        creating build/temp.macosx-10.9-x86_64-3.6/httpstan/lib/stan/src/stan
        creating build/temp.macosx-10.9-x86_64-3.6/httpstan/lib/stan/src/stan/lang
        creating build/temp.macosx-10.9-x86_64-3.6/httpstan/lib/stan/src/stan/lang/grammars
        gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ahartikainen/miniconda2/envs/httpstan_env/include -arch x86_64 -I/Users/ahartikainen/miniconda2/envs/httpstan_env/include -arch x86_64 -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -Ihttpstan -Ihttpstan/lib/stan/src -Ihttpstan/lib/stan/lib/stan_math_2.15.0 -Ihttpstan/lib/stan/lib/stan_math_2.15.0/lib/eigen_3.2.9 -Ihttpstan/lib/stan/lib/stan_math_2.15.0/lib/boost_1.62.0 -Ihttpstan/lib/stan/lib/stan_math_2.15.0/lib/cvodes_2.9.0/include -I/Users/ahartikainen/miniconda2/envs/httpstan_env/include/python3.6m -c httpstan/compile.cpp -o build/temp.macosx-10.9-x86_64-3.6/httpstan/compile.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized
        In file included from httpstan/compile.cpp:448:
        In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:435:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:104:33: error: 'operator=' is a private member of 'std::__1::ios_base'
            class _LIBCPP_TYPE_VIS_ONLY basic_ios;
                                        ^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:311:15: note: declared private here
            ios_base& operator=(const ios_base&); // = delete;
                      ^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:109:33: note: implicit copy assignment operator for 'std::__1::basic_ios<char, std::__1::char_traits<char> >' first required here
            class _LIBCPP_TYPE_VIS_ONLY basic_istream;
                                        ^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:113:33: note: implicit copy assignment operator for 'std::__1::basic_istream<char, std::__1::char_traits<char> >' first required here
            class _LIBCPP_TYPE_VIS_ONLY basic_iostream;
                                        ^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:126:33: note: implicit copy assignment operator for 'std::__1::basic_iostream<char, std::__1::char_traits<char> >' first required here
            class _LIBCPP_TYPE_VIS_ONLY basic_stringstream;
                                        ^
        httpstan/compile.cpp:1084:24: note: implicit copy assignment operator for 'std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >' first required here
          __pyx_v_stan_lang_in = std::stringstream(__pyx_t_4);
                               ^
        1 error generated.
        error: command 'gcc' failed with exit status 1

        ----------------------------------------
    Command "/Users/ahartikainen/miniconda2/envs/httpstan_env/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/bw/cqyhp7rs5l1_96nr8lsqyk400000gn/T/pip-build-qwhbrcvn/httpstan/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/bw/cqyhp7rs5l1_96nr8lsqyk400000gn/T/pip-68pzlgjf-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/bw/cqyhp7rs5l1_96nr8lsqyk400000gn/T/pip-build-qwhbrcvn/httpstan/

# Git clone fails

    git clone https://github.com/stan-dev/httpstan
    cd httpstan
    python setup.py install

error message

    running build_ext
    building 'httpstan.spsc_queue' extension
    creating build/temp.macosx-10.9-x86_64-3.6
    creating build/temp.macosx-10.9-x86_64-3.6/httpstan
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ahartikainen/miniconda2/envs/stan_http2/include -arch x86_64 -I/Users/ahartikainen/miniconda2/envs/stan_http2/include -arch x86_64 -Ihttpstan/lib/stan/lib/stan_math/lib/boost_1.62.0 -I/Users/ahartikainen/miniconda2/envs/stan_http2/include/python3.6m -c httpstan/spsc_queue.cpp -o build/temp.macosx-10.9-x86_64-3.6/httpstan/spsc_queue.o -O3 -std=c++11
    clang: error: no such file or directory: 'httpstan/spsc_queue.cpp'
    clang: error: no input files
    error: command 'gcc' failed with exit status 1

**Comment by ariddell** [comment]
Sorry, I need to add full instructions for building from source. You have to do this:

``
make protos
make cython
python setup.py install  # or python setup.py build_ext --inplace
``
