### ISSUE TITLE
Packages not uploaded automatically to pypi

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#124]
Since gnupg signing of packages is no longer encouraged by the PyPI admins, we can skip signing packages. This means we can upload packages automatically to PyPI with travis. This is nice since we only have to tag a release here and then make a single commit in `httpstan-wheels` to kickoff the process.

**Comment by ahartikainen** [comment]
Do we need to read some specific keyword? Also is there a need for some authentication?

**Comment by riddell-stan** [comment]
This is really easy to do. We can call `twine` to upload the package.

I need to create a token to authenticate travis when it uploads. https://pypi.org/help/#apitoken

**Comment by riddell-stan** [comment]
This is done in httpstan-wheels.
