### ISSUE TITLE
Compile models parallel

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/httpstan#168]
I think with some minimal imports from `numpy.distutils` there is a possibility to compile the model parallel.

https://docs.scipy.org/doc/numpy-1.16.0/reference/distutils.html

http://numpy-discussion.10968.n7.nabble.com/parallel-compilation-with-numpy-distutils-in-numpy-1-10-td38813.html

https://stackoverflow.com/a/55670555

**Comment by riddell-stan** [comment]
Interesting!
