### ISSUE TITLE
Cant run the example from the Usage instructions in README.md 

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/httpstan#172]
I decided to try out httpstan and was not able to get it up and running with the instructions in the README.

I tried on two different Ubuntu 18.04.2 environments and got the same results.

I installed it using 

`python3 -m pip install httpstan`

I was able to start it with `python3 -m httpstan`.

I then ran

```
curl -X POST -H "Content-Type: application/json" \
    -d '{"program_code":"parameters {real y;} model {y ~ normal(0,1);}"}' \
    http://localhost:8080/v1/models
```
That returned a very long `"compiler_output"` with warnings but I got the name, so I think this step is fine
```
"compiler_output": ...., "name": "models/ace4f406ec"}
```
I than ran
```
curl -X POST -H "Content-Type: application/json"     -d '{"function":"stan::services::sample::hmc_nuts_diag_e_adapt"}'     http://localhost:8080/v1/models/ace4f406ec/fits
```
and got

```
500 Internal Server Error

Server got itself in trouble
```

The server outputed the following message, if it helps: 
```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/rok/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/rok/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/rok/.local/lib/python3.6/site-packages/httpstan/views.py", line 299, in handle_create_fit
    "metadata": {"fit": schemas.Fit().load({"name": name})},
  File "/home/rok/.local/lib/python3.6/site-packages/marshmallow/schema.py", line 732, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/home/rok/.local/lib/python3.6/site-packages/marshmallow/schema.py", line 876, in _do_load
    field_errors=field_errors,
  File "/home/rok/.local/lib/python3.6/site-packages/marshmallow/schema.py", line 1157, in _invoke_schema_validators
    partial=partial,
  File "/home/rok/.local/lib/python3.6/site-packages/marshmallow/schema.py", line 777, in _run_validator
    validator_func(output, partial=partial, many=many)
TypeError: validate_result() got an unexpected keyword argument 'partial'
```

**Comment by ahartikainen** [comment]
While writing that msg, I noticed that this is a problem with marshmallow lib.

Please install older marshmallow

    pip install --pre marshmallow=3.0.0rc4

(Or is there 2 =, don't remember)

See https://github.com/stan-dev/pystan-next/issues/77 and https://github.com/stan-dev/httpstan/pull/171

Old msg:

Hi, I'm not currently on computer, but can you try `pystan-next`.

    pip install git+https://github.com/stan-dev/pystan-next

I have had some problems with httpstan on a commandline, but these are usually been my fault due to invalid commands.

**Comment by rok-cesnovar** [comment]
Yeah, that did it. Thanks @ahartikainen! Closing.
