### ISSUE TITLE
parse_cmdstan_help.py needs to be updated for newer CmdStan

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#173]
Reported https://discourse.mc-stan.org/t/cmdstanpy-ready-for-beta-testing/8792/23 . Not getting all the options from current version of CmdStan.

**Comment by ahartikainen** [comment]
What url/urls is used for parsing?

**Comment by riddell-stan** [comment]
It's the ``help-all`` output from cmdstan. If you compile any model into an executable and then run ``{{executable_name}} help-all`` you'll get the right output. Save the output to a file and then run `parse_cmdstan_help.py` on it.

**Comment by ahartikainen** [comment]
Maybe we could create a wikipage/doc to show how to do it (or is this already described somewhere?)
