### ISSUE TITLE
Release version with Stan 2.20

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#174]
Stan 2.20 is out. This has some key threading improvements. Might even solve some Windows issues (fingers crossed).

**Comment by ahartikainen** [comment]
Do we need to use numpy distutils here to link precompiled stuff?

**Comment by riddell-stan** [comment]
I think those changes are not in 2.20.

**Comment by ahartikainen** [comment]
https://discourse.mc-stan.org/t/stan-2-20-0-released/9797?u=ahartikainen

Also let's see if threading stuff works on Windows
