### ISSUE TITLE
GCC support on Linux

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/httpstan#212]
Any idea what causes the segfault on Linux with GCC (7, 8, 9).

Has it something to do with ChainableStack's initialization?

**Comment by riddell-stan** [comment]
We cover it on the forum: https://discourse.mc-stan.org/t/example-of-use-of-autodiffstacksingleton-stan-threads-related/10037

**Comment by ahartikainen** [comment]
Yes, I have been following the thread, but still, I have no idea why GCC would fail on Linux for Python but not for CmdStan. Is there some problem with how we link?
