### ISSUE TITLE
Boost macros are potentially not needed

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#214]
(There's nothing better than removing unused lines of code.)

Let's try removing one or both of these:

- BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
- BOOST_DISABLE_ASSERTS

See discussion: https://discourse.mc-stan.org/t/boost-defines/10087/9

**Comment by ahartikainen** [comment]
Let's try. We have Linux + Windows tests, but no macOS, so let's be careful if they affect it.
