### ISSUE TITLE
Server loop runs in main thread

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/httpstan#215]
I think current setup is a bit flawed.

The loop should run in the created thread, but it actually runs in the main thread. 

If we check the behavior of the `id(get_event_loop())` it does not update after calling `set_event_loop`.

**Comment by riddell-stan** [comment]
I think I see what you're saying.

The code looks OK to me (in main.py).

Things do work well right now. Is there some bug or problem created by 
the current behavior that you see?

**Comment by ahartikainen** [comment]
If the main loop is already running (ipykernel for example uses asyncio), then calling 

    loop.run_until_complete
    loop.run_forever

will raise RuntimeError, because the loop is already going.

The problem can be seen in 

```
def run(self) -> None:
        """Runs in a separate thread when ``start`` is called."""
        # This thread takes over control of the event loop.
        asyncio.set_event_loop(self.loop)
        self.loop.run_forever()  # will stop when ``stop`` is called
```

where 

```
asyncio.set_event_loop(self.loop)
```
does not work (it will not change loop, if the current loop is active).

The problem is, that all of this should be running in the new thread, the the main thread. But the thread is not created before `.start()` is called.


https://github.com/ipython/ipython/issues/11030

**Comment by ahartikainen** [comment]
Because, I think our intention is 

Create thread --> Start server in the new thread --> When exit, kill server and thread

**Comment by riddell-stan** [comment]
If the current setup is incompatible with (newer version of) IPython 
then I guess that's a bug. Have you confirmed that pystan-next breaks in 
IPython?

**Comment by ahartikainen** [comment]
Ipython works, jupyter notebook / hydrogen on atom does not.

**Comment by ahartikainen** [comment]
I'm just thinking, if those initial stuff can be called after the start is called? Or could we start the new thread already in pystan?

I just can't wrap my head around at what point Thread class creates a new thread.

Or are some of those functions callable without asyncio (let's not go there, I like asyncio)

**Comment by riddell-stan** [comment]
I recall reading the documentation for threading.Thread and asyncio 
carefully when I wrote that bit of code.

Clearly we need to be able to support jupyter notebooks though. Would be 
nice to have a test that verifies the correct behavior.

**Comment by ahartikainen** [comment]
I wonder if we could do this from the PyStan3 side? Create a new thread to call httpstan server?

**Comment by riddell-stan** [comment]
I'm not sure if I understand exactly what the problem is here. If there's an example of how the current setup breaks or does something undesirable, that would help me understand.

**Comment by ahartikainen** [comment]
Here is one issue in jupyter/notebook

https://github.com/jupyter/notebook/issues/4312

**Comment by riddell-stan** [comment]
Do you run into this problem when you use pystan 3 from jupyter? (I don't think I've tried to use it yet.)

**Comment by ahartikainen** [comment]
Yes, it can not start httpstan.

**Comment by riddell-stan** [comment]
Got it. I can reproduce the problem.

I do think that the `httpstan.main.Server` class could be removed entirely. PyStan 3 should take responsibility for figuring out how to manage the httpstan service.

I still don't understand what is going wrong. Have you found a discussion of why ``asyncio.set_event_loop(self.loop)`` does not actually set the event loop?

**Comment by ahartikainen** [comment]
There is a problem that jupyter notebook / atom editor / etc run their python on asyncio event loop. This means that the main loop is already running, and asyncio code does not allow multiple event loop running (in the same thread).

**Comment by riddell-stan** [comment]
Let's get rid of ``httpstan.main.Server`` entirely and deal with this in PyStan 3. It's something we should do anyway because there's no reason for ``httpstan.main.Server`` to be part of the httpstan source code.

We will have to rewrite the tests. But perhaps we can make use of pytest-asyncio to make things simpler.
