### ISSUE TITLE
Compile with Stan as a library (Stan 2.22)

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#217]
Stan 2.21 requires using TBB as an external library. We can no longer use the header-only approach.

Seems simplest to start with 2.20 and get things working here. We can look at how RStan does it. (I'm almost positive they do not do header-only.)

Fairly sure we have to abandon `pbr` and use something like numpy's install_clib.

Suggested path:

- [ ] Compile with Stan 2.19.1 without using header-only approach (try numpy build_clib first, it worked in the past)
- [ ] Move to Stan 2.22 "ensure[ing] that nothing of the AD tape global stuff gets compiled into the services", see discussion on https://github.com/stan-dev/math/issues/1306

**Comment by ahartikainen** [comment]
I don't think numpy's install_clib works with the current distutils.

PyStan 2 sundials update PR has one "working" solution which could be used. Basically only thing what is "edited" is for `.c` files. Similar procedure for C++ should work "out-of-the-box" with distutils.

**Comment by ahartikainen** [comment]
https://github.com/stan-dev/pystan/pull/637

**Comment by ahartikainen** [comment]
Should we also compile Sundials at setup and only link them to the model?

Then we could compile C++ and C in different steps.

**Comment by riddell-stan** [comment]
Eventually. I want to take this slow though. I think it was a mistake to make a release which didn't have linux or gcc support.

I also do want to identify a "standard" way of distributing compiled libraries, if one exists. If numpy's install_clib no longer works, then we should look at what packages which relied on that are doing now. If no other packages are doing what we are doing then we can, of course, develop a custom solution.

**Comment by ahartikainen** [comment]
Yeah, we need to find which package has C and C++ (with c++14).

**Comment by riddell-stan** [comment]
It may be worth looking at `poetry` for this. It looks like there is an undocumented way to add extra steps to the build phase. If we could manage to get to this to work we could build httpstan without the trouble of writing and maintaining a ``setup.py``. ``pbr`` lets us do this right now but we will have to abandon it in order to use anything remotely like numpy's `build_clib`.

Here's an issue in poetry's repo which describes the approach: https://github.com/sdispater/poetry/issues/1351

**Comment by riddell-stan** [comment]
This is no longer really relevant. stanc3 changes these considerations a bit.
