### ISSUE TITLE
Discard previous history for faster cloning with 1.0.0 release

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#243]
I'd like to move the history of `master` into a different branch ("0.10" or something like that). The first commit to `master` will be the 1.0.0 release. This will make cloning faster. This wouldn't normally be an issue but with httpstan it is (we store all of the Stan source in the tree). 

@ahartikainen sound OK?

**Comment by ahartikainen** [comment]
Sounds good. Do we have an idea how far normal clone goes and is there some argument to clone  command that limits the copied history?

**Comment by riddell-stan** [comment]
Done! @ahartikainen I made a commit for you which I hope looks OK. I think it should be enough for github (and other services inspecting the metadata) to register you as an author. You're also in ``AUTHORS.rst``.

**Comment by ahartikainen** [comment]
Looks good
