### ISSUE TITLE
Set up coveralls or codecov

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#257]
It would be good to have feedback about what needs coverage, what's missing.

**Comment by ahartikainen** [comment]
Both are great libs.

ArviZ uses coveralls (which needs https://docs.coveralls.io/parallel-build-webhook because we run tests multiple times; different libs)

**Comment by ahartikainen** [comment]
We changed from coveralls to codecov, so we can have the info on the PR.
