### ISSUE TITLE
Check test duration

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/httpstan#259]
There is simple way to see how long different tests run.

    pytest ... --durations=0

http://doc.pytest.org/en/latest/usage.html#profiling-test-execution-duration

0 -> show all timings (>0.01)
n -> show n slowests

I don't know if there is a way to log the durations somewhere.

**Comment by riddell-stan** [comment]
This is a great idea. We definitely want to track duration.

Perhaps we should come up with a plan to keep track of performance. Maybe there is another project that does this well? We could also create a ``httpstan-benchmarks` repository which is dedicated to tracking these things, at least at the release level.

**Comment by riddell-stan** [comment]
Measuring speed accurately is a big project. I think it probably needs its own repo. I think this can wait until a later date.
