### ISSUE TITLE
Readthedocs does not and will not support packages with code generation steps

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#261]
``readthedocs`` does not support packages that have a code generation step. There is no way to generate the code before running ``sphinx-build``. This seems unlikely to change.

It's possible that some sort of solution or hack might emerge, especially if we use `poetry` to build things in the future (likely). See this, for example, https://github.com/chrahunt/rtd-poetry

It's frustrating that travis can build our documentation but readthedocs cannot. On the other hand, readthedocs is free.

Currently we maintain a branch `readthedocs` which needs to be manually rebased every release. This is not desirable as it increases the labor required to make a new release.

**Comment by riddell-stan** [comment]
Another problem with readthedocs is that we cannot build and install httpstan (required for Sphinx to work). This is because readthedocs builders only have 1G of RAM.

**Comment by ahartikainen** [comment]
Do we have any alternatives? Can we use Stan resources?

**Comment by riddell-stan** [comment]
I sent an email to see if they'll let us build with more RAM. The alternative is to build the docs ourselves and upload them somewhere. This seems like a lot of work.

Also, readthedocs works great in other cases. This is a bit of an edge case.

**Comment by riddell-stan** [comment]
Fixed in last few commits. Lots of hacks required.
