### ISSUE TITLE
Fix language in docs Stan "model" not "program"

### ISSUE THREAD

**Issue by ariddell** [stan-dev/httpstan#27]
There's Stan "program code" but no such thing as a Stan "program".

**Comment by bob-carpenter** [comment]
The way I think of it, a Stan program implements a model.  For example, the Stan program
```
parameters {
  real y;
}
model {
  y ~ normal(0, 1);
}
```
implements a simple univariate standard normal model.

**Comment by ariddell** [comment]
Thanks @bob-carpenter , this makes sense.

**Comment by ariddell** [comment]
Need to switch endpoint too, from /programs/ to /models/
