### ISSUE TITLE
Explore using azure pipelines instead of rackspace for httpstan-wheels

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#278]
The release process for httpstan and pystan wheels uses rackspace. Wheels, after being built and tested, are uploaded to rackspace.

One alternative is to upload directly to PyPI. But this removes any manual review of the final release step.

It seems like scipy and scikitlearn are moving to azure pipelines, which has a private PyPI option.

**Comment by ahartikainen** [comment]
I have used azure pipelines at work and then "released" artifacts which can be downloaded.

**Comment by riddell-stan** [comment]
I hope multibuild figures out a way to build via github actions or azure. It would be nice to use a single service to build all the binaries (linux, macos, windows).

There is a multibuild competitor which we could also consider: https://github.com/joerick/cibuildwheel

**Comment by ahartikainen** [comment]
What tricks multibuild does? Is there something special what can not be done by "manually" creating the wheel?

**Comment by riddell-stan** [comment]
multibuild is more configurable than cibuildwheel. It's easy to tell multibuild that we have to run `make` and then run `poetry build`, for example.

It should be easy to switch over to GitHub Actions or Azure Pipelines. It might be easier to start with something simpler, however. We could try switching over the ordinary tests from pystan-next, for example. If something goes wrong there's no real problem.

I'm leaning towards trying out GitHub Actions first since I do not want to create yet another account.

**Comment by riddell-stan** [comment]
Solved for now. We now upload directly to PyPI in httpstan-wheels.
