### ISSUE TITLE
Python protobuf barely used

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#289]
We only use a single function from the Python protobuf library, ``google.protobuf.internal.encoder._EncodeVarint``. It's a pure-Python function which we could include in a utilities module.

I believe this is the entirety of it:

```
def _VarintEncoder():
  """Return an encoder for a basic varint value (does not include tag)."""

  def EncodeVarint(write, value, unused_deterministic=None):
    bits = value & 0x7f
    value >>= 7
    while value:
      write(six.int2byte(0x80|bits))
      bits = value & 0x7f
      value >>= 7
    return write(six.int2byte(bits))

  return EncodeVarint
```

Found in https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/internal/encoder.py

The task here would be to rewrite this such that `six` is not required.

**Comment by ahartikainen** [comment]
Is there any performance difference between python and cython(?) for this function?

**Comment by riddell-stan** [comment]
Probably not.

There is one additional difficulty. Although httpstan does not use the Python protobuf files, e.g., `httpstan/callbacks_writer_pb2.py`, PyStan does. And this file requires the protobuf python library.

**Comment by ahartikainen** [comment]
So we could use this, or how pystan3 uses python-protobuf?

**Comment by riddell-stan** [comment]
pystan3 imports httpstan.callback_writers_pb2.py (even though httpstan does not). Is that your question?

A cleaner solution, IMHO, would be to have pystan3 generate its own callback_wriers_pb2.py. Then it could depend on the python protobuf and we could drop it as a requirement for httpstan.

**Comment by riddell-stan** [comment]
The length-prefix encoding is now done in C++. If we end up keeping protobuf we could revisit this at some point.
