### ISSUE TITLE
CI providers

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/httpstan#304]
So there are a few different choices to be made

# Github actions
- Native
- Step-by-step workflow
- Conditional steps
- Job timelimit 6h
- Workflow timelimit 72h
- 20 concurrent workflows
- Linux, macOS, Windows
- Possibility for artifacts
- Free use: 2000 min / 19 days

https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions

# Azure DevOps (with NumFocus)
- Step-by-step workflow
- Conditional steps
- Job timelimit xh
- Workflow timelimit xh
- X concurrent workflows
- Linux, macOS, Windows
- Possibility for artifacts

**Comment by riddell-stan** [comment]
My two cents:

- Faster builds would be nice. At least 10% faster? macOS especially.
- We don't need artifacts. We can upload directly to PyPI.
- Being able to do all builds (linux, macos, win) in a single place would be nice. In theory, travis-ci allows this. Windows is in beta.
- Being able to create an organizational / team account would be great. The new travis-ci.com seems to allow this. Appveyor allows this.

**Comment by riddell-stan** [comment]
GitHub Actions is out right now because they don't support doing builds of pull requests from outside the repository.

**Comment by ahartikainen** [comment]
Why faster builds, time limit thing?

**Comment by riddell-stan** [comment]
All other things being equal, I think (much) faster builds would be 
useful. For example, when there are multiple PRs which depend on each 
other, it's annoying to have to wait 30m to an hour for a test to complete.

**Comment by riddell-stan** [comment]
I think it is possible to run tests on pull requests using GitHub Actions. (The limitation only concerns private forks -- which doesn't concern us here.) https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories

**Comment by riddell-stan** [comment]
Let's close this for now. I started this discussion when travis-ci was broken and there was some urgency to find a replacement. Now travis-ci is working again.

We can open new issues which describe distinct problems (in need of solutions which a CI provider may offer).

**Comment by riddell-stan** [comment]
One thing GitHub Actions could do for us would be replacing httpstan-wheels. See #362.

Speeding up builds generally would be a separate issue, I think.

**Comment by ahartikainen** [comment]
We should revisit this due to the current situation with travis and OSS.

What if we move testing first to Actions?

Following a similar workflow as with Travis is doable, but I like more how Actions splits jobs into chunks.

**Comment by riddell-stan** [comment]
I don't object to switching to actions. I don't think it matters too much who we use to run the tests.

I do think we should keep travis around until we know for certain that the replacement is working.

**Comment by ahartikainen** [comment]
Ok, currently travis doesn't run, because all the oss credits have been used.

**Comment by riddell-stan** [comment]
Fixed in #498 .
