### ISSUE TITLE
CVODES-related functionality unsupported

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#311]
Now that we have a strategy for building and packaging shared libraries, it should not be difficult to resolve this.

**Comment by ahartikainen** [comment]
Should we combine cvodes .o files to .so or just use the .o as we do in PyStan2?

We need paths to .o/.so files and then feed them to model compilation step.

Should we use `make` or python based solution?

**Comment by riddell-stan** [comment]
I haven't looked at this closely yet. I'm thinking we can adopt the same strategy we used with protobuf and will adopt with tbb. We'll compile the shared library and then use rpath to point to it.

**Comment by ahartikainen** [comment]
I think we currently compile a static version of the CVODES. 

So do we make it shared and link it at the runtime?

**Comment by riddell-stan** [comment]
I think using the shared library would decrease the model compile time.

**Comment by ahartikainen** [comment]
That might be true. But how much does the compilation time increase if we precompile CVODES?

**Comment by riddell-stan** [comment]
I'm not sure I understand. We would distribute a shared library inside 
the wheel. Nobody would need to compile it.

**Comment by ahartikainen** [comment]
True. Yeah I think that would work nicely now when we need to link to other libs too.

I was thinking of model compilation vs precompilation (time when cvodes is compiled) structure. What we do currently in pystan2.

**Comment by ahartikainen** [comment]
Would that mean we can drop sundials folder from stan-math? (excluding include file?)

**Comment by ahartikainen** [comment]
I have tried CVODES enabled master

    git checkout 30bb10f6

calling `make` first complains that find can not find two paths (but apparently these are downloaded and created in the script)

But, the CVODES compilation is never called (and I can not find any sundials files under httpstan/lib.

The tests fail with saying that they can not find sundials related files.

Is there line missing in Makefile?
