### ISSUE TITLE
Upgrade Stan library to 2.22

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#314]
Upgrading to Stan 2.23 will take some time. Let's break it down into these steps:
- [x] Get CVODES working #311 
- [ ] Upgrade to Stan 2.22, use TBB
- [ ] Use stanc3

**Comment by ahartikainen** [comment]
Do we also want to use precompiled model code?

**Comment by riddell-stan** [comment]
Eventually. I think the immediate goal should be to get things working 
with Stan 2.23.
