### ISSUE TITLE
Makefile is hard to read, contains non-idiomatic rules

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#328]
The `Makefile` has a few non-fatal errors:
- [ ] There's at least one rule that can be simplified in the Makefile.
- [ ] There needs to be an obvious rule indicating that the math tarball should be extracted before compiling libsundials.

We might be able to use -j 4 to speed things up as well.

**Comment by ahartikainen** [comment]
Why we don't use cmake?

**Comment by riddell-stan** [comment]
I think a better solution may be to directly use CmdStan's Makefile to build the shared libraries and copy them into place. This would be better because we would not have to maintain the Makefile over time.

**Comment by riddell-stan** [comment]
Fixed in df01dbebd3f37c32dc8e8bc476ed7541ab186849. Note we use Stan Math's rules, not CmdStan's rules.
