### ISSUE TITLE
Use precompiled headers to speed up compilation

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#334]
See https://github.com/stan-dev/cmdstan/issues/872

**Comment by riddell-stan** [comment]
@rok-cesnovar am I correct in assuming that g++ will detect and use the precompiled header without any special configuration whereas clang requires the `-include-pch` flag? I take it there's no hope for a single standard being supported anytime soon?

**Comment by ahartikainen** [comment]
Will g++ fail if it gets `-include-pch`?

**Comment by rok-cesnovar** [comment]
> am I correct in assuming that g++ will detect and use the precompiled header without any special configuration whereas clang

Yes, that is correct. 

For g++ you just need to make sure the precompiled header is a dependency somewhere so it gets built. clang needs `include-pch` and g++ fails with `include-pch` as far as I remember.

Hence this beautiful line in https://github.com/stan-dev/cmdstan/blob/develop/make/program#L28

**Comment by riddell-stan** [comment]
@rok-cesnovar Thanks. Good to know. This should be easy to add for gcc at least.

**Comment by riddell-stan** [comment]
Compilation speed is a problem. `httpstan` is 5x slower right now. Before any precompiled headers:

CmdStan 2.24:

```bash
hyperfine --prepare 'rm -f examples/normal/normal' 'make examples/normal/normal'
Benchmark #1: make examples/normal/normal
  Time (mean ± σ):      9.461 s ±  0.161 s    [User: 8.956 s, System: 0.498 s]
  Range (min … max):    9.260 s …  9.723 s    10 runs
```

httpstan 2.1.0 / d496883214cd8d73c5af13913260afac81a68dca

```bash
hyperfine --prepare 'rm -rf ~/.cache/httpstan/2.1.0/models/c7cc3vcc' 'curl -H "Content-Type: application/json" --data "{\"program_code\":\"parameters {real y;} model {y ~ normal(0,1);}\"}" http://localhost:8080/v1/models'
Benchmark #1: curl -H "Content-Type: application/json" --data "{\"program_code\":\"parameters {real y;} model {y ~ normal(0,1);}\"}" http://localhost:8080/v1/models
  Time (mean ± σ):     47.407 s ±  1.758 s    [User: 8.5 ms, System: 4.5 ms]
  Range (min … max):   44.661 s … 48.860 s    10 runs
```

**Comment by riddell-stan** [comment]
@rok-cesnovar Any tips on "debugging" compile times? Superficially I don't think I'm doing anything that different than cmdstan. Compiling should take longer but not 5x longer.

Also, is there any way to detect if the precompiled header is actually being used? I'm not seeing any impact right now (in my testing setup).

**Comment by riddell-stan** [comment]
I'm assuming for the moment that I'm not doing something right.

The gcc documentation says that precompiled headers need to be created in a very specific way: https://gcc.gnu.org/onlinedocs/gcc/Precompiled-Headers.html

**Comment by syclik** [comment]
sorry for jumping in mid-stream.

My experience: precompiled headers don't actually help that much. It's hard to actually keep it in synch. But... I've never seen it hurt either.

If it's taking 5x, maybe taking a step back would help. If you could either describe how it's built or point me to it, I can dig into it. 

In CmdStan, there are actually three steps that happen:

1. The `main.cpp` gets compiled to a `main.o`; this takes 47 seconds (on my Mac), but is a one-time cost. 
2. The generated `.hpp` is compiled to a `.o` file. This takes about 8 seconds (for a simple model).
3. Link an executable using the `main.o` and the `.o` from the generated file. This takes about 0.1 seconds.

Are you doing those steps separately? If not, you might see what you're seeing.

**Comment by riddell-stan** [comment]
Thanks Daniel.

I think we're on the same page now. I suspected that httpstan was 
missing an equivalent of step 1 (compile main.o).

Clearly we need to adopt the cmdstan strategy and separate out the 
"main.cpp" and the generated "model.hpp".

I'm confident that this can be done. It may be easier to do this using 
pybind11 instead of Cython (see #403).

One thing which would help me is a betting understanding of how main.cpp 
is able to reference a model which is defined in a file which the 
compiler has never seen. I gather this happens in command.hpp#61? Is 
there any additional documentation I can read?

**Comment by rok-cesnovar** [comment]
> precompiled headers don't actually help that much

They help, but you definitely need the pre-compiled main.o beforehand. The precompiled header still brought cmdstan compiling down for a factor of 2 (from 15seconds to 7 for the example model). But yes, 8s in 40+s is not much.

**Comment by syclik** [comment]
Thanks for the clarification!

**Comment by syclik** [comment]
@riddell-stan, yes, you found it:
https://github.com/stan-dev/cmdstan/blob/develop/src/cmdstan/command.hpp#L60

It's forward-defining something that's defined in a different translation unit. And using C++ polymorphism. At some point, we had the model actually subclass a base class. It used to not be done this way (well... practically).

**Comment by riddell-stan** [comment]
Closing this in favor of #461. When I opened this issue originally I mistook the source of the compilation time problem.

**Comment by riddell-stan** [comment]
Now down to 26.8 seconds from 35.0 seconds (on my machine). Progress but not near 9.5 seconds (cmdstan).
