### ISSUE TITLE
Require Python 3.8 for macOS to avoid Catalina issues

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#340]
If we require Python 3.8.2 or higher on macOS, we don't have to deal with the multiprocessing issue that seems to be circulating. See https://github.com/matplotlib/matplotlib/issues/15410#issuecomment-625027757

**Comment by ahartikainen** [comment]
Sounds fine

**Comment by riddell-stan** [comment]
It looks like poetry doesn't let us fix this problem directly. macOS users on Catalina will have to work around this problem.

**Comment by ahartikainen** [comment]
There is also an option to manually turn on forking on macOS. pymc3 fixed the problem this way.
