### ISSUE TITLE
Remove dependency on marshmallow and webargs

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#371]
webargs and marshmallow pull in a lot of packages. We barely use them. They can likely be replaced with zero or one third-party package(s).

Candidates:
- [typesystem](https://www.encode.io/typesystem/)
- [orjson](https://github.com/ijl/orjson)
- zero third-party packages, just use dataclasses

**Comment by ahartikainen** [comment]
I was just reading json packages a few weeks ago.

orjson looks interesting, it returns bytes and is fast.

The orjson github has also interesting comparison with different json libs.

**Comment by ahartikainen** [comment]
What would we need if we would go with the dataclasses?

**Comment by riddell-stan** [comment]
There's a blog post that describes an approach, <https://instagram-engineering.com/types-for-python-http-apis-an-instagram-story-d3c3a207fdb7?gi=8b43c185b70>.

**Comment by riddell-stan** [comment]
marshmallow is reasonably lightweight, especially compared to the alternatives. dataclasses (intentionally) do not support validating input types. Closing for now.
