### ISSUE TITLE
Cython is no longer a build dependency

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#372]
There are some lines in the repo that assume Cython is a build dependency. Since we started using stanc, it no longer is a build dependency. Those lines that assume it is should be removed.

**Comment by ahartikainen** [comment]
We don't build anything with cython at build anymore? Interesting.

**Comment by riddell-stan** [comment]
This turns out to be somewhat more complicated than I expected. We do need to have some sort of extension module as part of the package, otherwise the wheel build machinery will not detect that this package needs a platform-specific wheel. See https://stackoverflow.com/a/53463910

**Comment by riddell-stan** [comment]
For now we'll keep the dependency, see #376
