### ISSUE TITLE
Debugging segfaults is difficult

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#390]
Debugging segfaults is really difficult when we run the sampler in a different process. By contrast, if everything runs in a process with no multithreading/multiprocessing, debugging with `gdb` is remarkably easy.

Here's a solution. If the user sets the environment variable ``HTTPSTAN_DEBUG`` to a truthy value, disable all multiprocessing/multithreading associated to the call to the stan::services functions. This means that the call to the ``fits`` endpoint will block. No parallel sampling will be possible.

If ``HTTPSTAN_DEBUG`` is set, one would also *not* redirect stderr or stdout.

**Comment by ahartikainen** [comment]
Is it enough to change executor in here https://github.com/stan-dev/httpstan/blob/2730a8c784c69aeb38a6cd2eaecae25a417968cf/httpstan/services_stub.py

from

    executor = concurrent.futures.ProcessPoolExecutor()

to use one with threading with one worker?

    threading= concurrent.futures.ThreadPoolExecutor(max_workers=1)

So changing line 92

    future = asyncio.get_running_loop().run_in_executor(executor, lazy_function_wrapper_partial)

Problem is that the executor is called at the import step, but threading executor should be called at the function call step.

So maybe a line before 92 in a function to temporary override the executor

    if os.environ.get("HTTPSTAN_DEBUG"):
        executor = concurrent.futures.ThreadPoolExecutor(max_workers=1)

**Comment by riddell-stan** [comment]
Using any threads at all makes debugging more difficult. The goal is to not use any threads other than the main thread.
