### ISSUE TITLE
Wheels are not automatically uploaded

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#407]
To replicate the functionality of the `httpstan-wheels` repository we need to have wheels built and uploaded on linux and macOS whenever there is a new (signed) tag.

I'm going to use this issue to collect ideas and links to repositories doing this---or parts of this.

- https://github.com/joerick/cibuildwheel (claims to work already)
- pypa's https://github.com/pypa/gh-action-pypi-publish/ -- just the publishing step.
- https://github.com/innobi/pantab/blob/master/.github/workflows/pythonpublish.yml seems like a working example
- https://github.com/matham/ffpyplayer/blob/master/.github/workflows/pythonapp.yml another working example

**Comment by riddell-stan** [comment]
I don't see any way to solve this in the short term for httpstan. We can certainly get it working for pystan though.

**Comment by ahartikainen** [comment]
https://github.com/marketplace/actions/python-wheels-manylinux-build

I think this could work for us?

**Comment by riddell-stan** [comment]
That looks interesting. I opened an issue in httpstan-wheels, https://github.com/stan-dev/httpstan-wheels/issues/59 . The first step is to get things working there. Then we can consider moving things here (and deleting httpstan-wheels).
