### ISSUE TITLE
Python 2.7 support?

### ISSUE THREAD

**Issue by zachmayer** [stan-dev/httpstan#41]
I know python 3 is the future, but is there any possibility of a python 2.7 compatible version of httpstan?

I'd be happy to make a PR and start fixing broken tests, but thought it'd be best to have a discussion first.

**Comment by ariddell** [comment]
Nope! Python 2.7 is EOL.

**Comment by bob-carpenter** [comment]
@zachmayer May I ask why you're inquiring about Python 2.7?  Are you in a situation where you can't upgrade to Python 3?  If so, what is blocking the upgrade path?
