### ISSUE TITLE
Bug: Request Entity Too Large

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/httpstan#417]
See #416 and https://github.com/stan-dev/pystan-next/issues/135

This issue is for `413 Request Entity Too Large` -error when httpstan tries to send too large data. (See pystan issue for the model and data).

httpstan version: '2.0.4' (pypi)
pystan version: '3.0.0-beta.1' (pypi)
OS: Ubuntu (WSL1)

**Comment by ahartikainen** [comment]
See https://github.com/aio-libs/aiohttp/pull/1414

**Comment by ahartikainen** [comment]
See the docs here https://docs.aiohttp.org/en/stable/web_reference.html

**Comment by ahartikainen** [comment]
Changing this 

https://github.com/stan-dev/httpstan/blob/8781bee339ab174568062a2576a6132c2f2d3348/httpstan/app.py#L39

to 

    app = aiohttp.web.Application(client_max_size=None)

Fixes the problem and model compiles and samples fine. Not sure if this is a safe solution?

**Comment by riddell-stan** [comment]
Looks like 1 megabyte (1024 ** 2 bytes) is the current client max size. I can see how that would easily be exceeded. Let's set it to 1024 ** 3 (1GiB). We might also add a test with (>1MB) data.

**Comment by ahartikainen** [comment]
1GB sounds ok.

What are considered when talking about app size?

If we use simple model with 5gb of data --> app size is 5gb * x where x > 1

?

**Comment by riddell-stan** [comment]
I'm not sure I understand. The client max size is the maximum size of 
the body associated with a POST request. The only things that we POST 
are data and program code. Data is the only thing that can be bigger 
than a MB. I can't imagine it would ever be bigger than 1 GiB.

**Comment by ahartikainen** [comment]
I could imagine it being larger. We have had some examples on the discourse with data sizes in 2-6gb.

https://discourse.mc-stan.org/t/additive-random-effect-models-with-large-data-sets/8868

But these are rare cases.

**Comment by riddell-stan** [comment]
I'm not sure a `client_max_size` of `None` is allowed. It seems to work but the documentation doesn't mention it any more.
