### ISSUE TITLE
Block codecov emails?

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#428]
I don't find codecov particularly helpful.

It doesn't really bother me though -- except for the emails. Is there a recommended way of preventing emails from being sent? Does one just block the codecov user in one's account settings?

cc @ahartikainen

**Comment by ahartikainen** [comment]
You can set the behaviour in `.codecov.yml` or I guess in codecov.io

**Comment by riddell-stan** [comment]
Is it alright if I remove it? I find it distracting for a project at this stage of development. Plus we already have the minimum test percentage threshold in travis.

I'm happy to keep it if other contributors or potential contributors are interested in it.

**Comment by ahartikainen** [comment]
Sure, I check codecov.io page for line-by-line info if I need to check anything related to that.

**Comment by ahartikainen** [comment]
Changing this in `codecov.yml` should be enough

    comment: false
