### ISSUE TITLE
Option to turn-off samples caching

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/httpstan#432]
Could we add an option to start the server without caching samples? 

I like the models caching feature, but a httpstan instance I am running on an AWS instance would benefit from not caching samples. I let a bunch of users access that instance and if someone unnecessarily requests a too large number of samples (100k or something) that clogs up the system.

This may already be available, I apologize in that case.

**Comment by riddell-stan** [comment]
If you don't specify a random seed there will be no caching (for obvious 
reasons).

I think caching deterministic results makes sense. It's a great feature. 
If there are a lot of users who have problems with it (>1%), it might 
make sense to add an option though.

What's the specific problem? Is it disk space usage? I think the plan 
all along was to setup a LRU cache or something so we never used more 
than, say, 1G of disk space.

**Comment by rok-cesnovar** [comment]
> Is it disk space usage?

Yes. I am running this on an AWS instance and caching is the only reason for me to reserve more disk space I otherwise don't require. 

Its definitely a great feature, not denying that. 

Maybe you can just point me to where would be the simplest to turn this off and I can do that on a fork and build httpstan from source. I don't have a problem with that if this isn't a general feature.

**Comment by riddell-stan** [comment]
Just make `dump_fit` a no-op. The function is in cache.py

**Comment by riddell-stan** [comment]
Ignore the last message. (I deleted it.) This might be more complicated than I thought.

I don't think httpstan removes fits which are uncachable. This should happen on shutdown and maybe on startup.

**Comment by riddell-stan** [comment]
@rok-cesnovar A quick fix would be to set up a cron job to run every minute which would delete any files older than 1 hour in the httpstan cache directory.

**Comment by rok-cesnovar** [comment]
Ok, that is a great idea. Thanks! Feel free to close the issue.

**Comment by rok-cesnovar** [comment]
https://github.com/stan-dev/httpstan/issues/435 would fix this so I am closing this. Thanks for the interim solution idea.
