### ISSUE TITLE
Fits accumulate without limit

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#434]
Fits are never deleted. This is a problem for people who are making large fits.

Keeping the most recently-used N fits would be a quick fix to this problem.

(This is also a problem for models.)

**Comment by ahartikainen** [comment]
I have couple of questions for cache

- Do we have a function to clear cache?
- Should we have an option to disable cache?
- Can we set memory limit for cache?
    - Disable cache for too big fits?
- Can we set compression for saved fits/models?
- Where should we save the list of N recently used fits (which is thread-safe?)

**Comment by riddell-stan** [comment]
There are no documented answers to these questions. You'd have to read the code.

This is a reasonably complex topic and a complete solution would probably need a design document.

Most fits take about 1M to 10M. I think we should aim to 2GB max.

A quick fix would be to do the following every time the httpstan aiohttp `app` starts: Walk through the cache directory and delete fits (starting with the oldest) until we have, at most, 100 fits left. This task can be run in the background.

**Comment by riddell-stan** [comment]
We can also recommend that people simply delete their httpstan cache directory every now and then.

**Comment by riddell-stan** [comment]
Closing in favor of #435. I think people will understand that they need to clean up after themselves.
