### ISSUE TITLE
Read speed comparison of protobuf vs. json (simdjson) is not available

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#437]
If PyStan can read JSON-encoded messages from Stan about as fast as it can read Protobuf-encoded messages from Stan, we should switch to JSON since we would not have to ship the protocol buffers libraries and developers would not need to learn all about protocol buffers.

**Comment by ahartikainen** [comment]
What would be a good benchmark for this?

What are the common sizes for our messages?

Can we compress our messages with gzip?

Adding these to headers

    Content-Encoding: gzip
    Content-Length: X

https://stackoverflow.com/questions/32787358/json-data-compression-for-http-post

**Comment by ahartikainen** [comment]
Could we also try in other direction, 100k parameters with 500 draws etc. 

I just had one user with this problem (with 1gb cvs reading). pandas just froze, finally reading with python tools was the fastest solution.

**Comment by riddell-stan** [comment]
Almost done with this. simdjson beats protobuf by a bit.
