### ISSUE TITLE
Linear regression test lacks random seed

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#443]
Test fails (infrequently), see https://travis-ci.com/github/stan-dev/httpstan/jobs/380120258

**Comment by ahartikainen** [comment]
Seed will probably fix this (Other way would have an possibility to loop n times if test fails).

Is there any better way to handle that test?

Can we calculate posterior credibility interval that should contain the real value?

**Comment by riddell-stan** [comment]
There's a pytest plugin which will let you mark tests that might fail once in awhile.

I think it might be easiest to fix a random seed. We can depend on Stan for more serious testing of the algorithm.

**Comment by ahartikainen** [comment]
Closed by #445
