### ISSUE TITLE
Import setuptools at init

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/httpstan#448]
Our package needs `setuptools`. And recently there have been warnings that `setuptools` should be imported before the `distutils`.

```
.../python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: 
Distutils was imported before Setuptools. 
This usage is discouraged and may exhibit undesirable behaviors or errors. 
Please use Setuptools' objects directly or at least import Setuptools first.
```

Following our import path (from `app.py`) there is import for `webargs`, which imports `distutils` in their init.

https://github.com/marshmallow-code/webargs/blob/dev/src/webargs/__init__.py

To fix this issue, I suggest that we import `setuptools` at `__init__.py` and delete it after import

    import setuptools
    del setuptools

This procedure makes sure that our library will import `setuptools` first and then `distutils`. It is not foolproof, but at least works when used normally.

**Comment by riddell-stan** [comment]
I'm sure I'm not alone in not liking adding hacks like this.

Can we find a root cause of this? Why is webargs importing distutils? 
Are they unwilling to address the problem they are creating?

We could also reopen the issue which discussed removing webargs as a 
dependency. Removing webargs might be much easier than removing marshmallow.

**Comment by ahartikainen** [comment]
Yeah, this hack is not nice.

They have this

    from distutils.version import LooseVersion

also, this problem doesn't affect them, because they don't use setuptools (at runtime).

**Comment by riddell-stan** [comment]
Perhaps webargs could be persuaded to switch to setuptools's distutils's LooseVersion.

Removing the dependency on webargs would be great though. Getting rid of marshmallow will take work. Getting rid of webargs might be much easier.

**Comment by riddell-stan** [comment]
I suspect this is going to be resolved somehow. Lots of people are affected by this. See https://github.com/pypa/setuptools/issues/2230

If it doesn't get resolved, let's open a new issue to remove the dependency on webargs.
