### ISSUE TITLE
Add information for in-place installation

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/httpstan#451]
Should we add information how to install httpstan "in-place" (same as `pip install -e`)

https://github.com/stan-dev/httpstan/blob/main/doc/installation.rst

Something like this (I added step 3, but it is not really part of installing in-place, more of a dev-thing)

```
# Installation from source for development

# 1. Create a virtual env
python3 -m venv httpstan-development
source httpstan-development/bin/activate

# 2. Clone forked repository
git clone https://github.com/<username>/httpstan

# 3. Add remote repository
cd httpstan
git remote add upstream https://github.com/stan-dev/httpstan
git fetch --all

# 4. Build shared libraries and generate code
python3 -m pip install mypy-protobuf==1.21 poetry
make

# 5. Build the httpstan wheel
python3 -m poetry build

# 6. Install the library in-place
python3 -m poetry install
```

**Comment by riddell-stan** [comment]
This seems like something that could be documented in the discussion forum in response to a prospective developer having trouble.

Or one could make an independent post, like I did with the Jupyter notebook fix.

It's also a poetry issue -- poetry doesn't have an equivalent `pip install -e`. It's a known issue, I think.

**Comment by riddell-stan** [comment]
httpstan does not build anything in-tree anymore (except for the "empty" module to trigger binary wheels)
