### ISSUE TITLE
Many duplicate flags in call to gcc/clang

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#462]
Here's one of distutils' calls: ``x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC ...``

Several flags are duplicated including `-g`, `-O2`, `-fwrapv`. I'm not sure what library is causing this or if it can be fixed. It is confusing.

**Comment by ahartikainen** [comment]
Going through that rabbit hole... takes time https://github.com/python/cpython/blob/master/Lib/distutils/unixccompiler.py

**Comment by riddell-stan** [comment]
Looks like I'm not the only one "flabbergasted" by this: https://stackoverflow.com/questions/51019043/tidying-up-the-cython-build-flags-used-by-gcc

As there's no standard way of fixing this, I'm going to close this.
