### ISSUE TITLE
Compilation and/or linking is slow

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#471]
Time required to compile and link a simple model (`parameters {real y;} model {y ~ normal(0,1);}`) on an old laptop (ThinkPad X260).

- CmdStan 2.24: 9 seconds
- PyStan 2.19.1: 75 seconds
- httpstan 2.1.0: 47 seconds
- httpstan 2.2.0: 27 seconds

Clearly progress is being made. httpstan is still much slower than cmdstan.

Things to try:

- [ ] Compile without `-g` set
- [ ] Link using static libraries (like cmdstan).

**Comment by ahartikainen** [comment]
Is that 9 seconds run in serial or with `-j`?

How many libraries we compile?

**Comment by riddell-stan** [comment]
This is just the very final step, i.e., the 
`pystan.StanModel(model_code=code)` step.

**Comment by riddell-stan** [comment]
I don't think anyone has the appetite for doing work on this. Upgrading to the new version of pybind might help. I can't recall if there is any opportunity for parallel compilation. I don't *think* there is---we only compile the model's .hpp file and then link it.
