### ISSUE TITLE
Run the model through the stanc3 autoformatter before hashing

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/httpstan#483]
This might already be in use in which case I apologize. 

stanc3 offers auto formatting for Stan models through the `--auto-format` argument. It might be worth it to run the model through the auto formatter before hashing it for the purpose of caching.

Currently the auto formatter does not retain comments which means that we can not format the users models, but a preprocessing step to hashing might be worth it.

**Comment by riddell-stan** [comment]
I agree that hashing something different than the model code is an excellent idea. (I asked for a a comment-less "version" of the model code from the stanc2 folks several years ago.)

Hashing after --auto-format sounds like a minor improvement. At least models which differ only in terms of whitespace would have the same hashes.

Can we do any better? Can stanc3 give us a comment-less AST? Or should we just hash the C++ code?

**Comment by rok-cesnovar** [comment]
Actually, current —auto-format does not retain comments. So the way it works now is what you want.

We will add comments to AST at some point so we can also auto format for the user (in an IDE for example). But we do not do that right now.

**Comment by rok-cesnovar** [comment]
maybe there was a misunderstanding now that I read your comment again. By autoformatting I mean that both the input and output are a Stan model. No C++ in play here.

**Comment by riddell-stan** [comment]
Ideally we want to hash something that is insensitive to whitespace and 
comments.

Sounds like stanc autoformat will (eventually) be sensitive to comments.

What about hashing the generated C++ instead (with some placeholder 
model name)? Wouldn't that be insensitive to whitespace and comments in 
the original stan model code? Or am I missing something?

**Comment by rok-cesnovar** [comment]
> Sounds like stanc autoformat will (eventually) be sensitive to comments.

Yes. Though we might support both, that has not been discussed yet.

> What about hashing the generated C++ instead (with some placeholder
model name)?

Yeah, that would also work. You can also use the AST or MIR that both can be printed by the stanc3. But since you already have the C++ generated code that is probably easiest.

**Comment by riddell-stan** [comment]
The nice thing about hashing the model code is that we get a hash for 
arbitrary code, even code with syntax errors.

If we hash the C++ code the calculate_model_name function is going to 
get much more complicated.
