### ISSUE TITLE
Use fast lz4 compression for fits

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#485]
For a (very) large fit, gzip fast takes 12 seconds, gzip default takes 47 seconds.

**Comment by ahartikainen** [comment]
Fast means we would not do compression?

There are couple options which we could consider

Because we only do compress/decompress we could use 

https://pypi.org/project/mgzip

```
import mgzip

with mgzip.open(path, "wb") as f:
    f.write(fit_bytes)

with mgzip.open(path, "rb") as f:
    fit_bytes = f.read()
```

or

https://github.com/Blosc/python-blosc
https://github.com/Blosc/bloscpack

```
import bloscpack

bloscpack.pack_bytes_to_file(fit_bytes, path)

fit_bytes = bloscpack.unpack_bytes_to_file(path)
```

**Comment by riddell-stan** [comment]
I had the lowest (fastest) setting in mind.

If we want to use a third-party package, I believe lz4 is the fastest 
right now.

**Comment by riddell-stan** [comment]
We should use lz4. It's six times faster than gzip (gzip fast mode). Compression is about the same.
