### ISSUE TITLE
Wheels are poorly tested

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#488]
It doesn't look too hard to switch over to cibuildwheel from multibuild. See https://github.com/pybind/python_example

Doing so would eliminate numerous headaches. We could delete the `httpstan-wheels` repository, for example.

See also this discussion of new pybind11 distutils tools: https://iscinumpy.gitlab.io/post/pybind11-2-6-0/

**Comment by ahartikainen** [comment]
What was the problem last time we wanted to change to cibuildwheel?

**Comment by riddell-stan** [comment]
I don't recall what the problem was with cibuildwheel.

I don't see a solution to this problem in the short-term. We test the linux version here. We test the macos version here and test the macos wheel in httpstan-wheels. I think this is going to have to be good enough for now.
