### ISSUE TITLE
docs: Full list of supported platforms and architectures missing

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#501]
We do not have a list of supported platforms and architectures. I believe it's

Supported platforms:

- x86-64 Ubuntu Linux 20.04
- x86-64 macOS with macOS 11.14

Supported Python versions :

- CPython 3.7
- CPython 3.8
- CPython 3.9

Once we upgrade pybind11 to the current version I believe we can support PyPy7 as well.

Platforms to evaluate:
- Alpine Linux
- Arch Linux
- Centos
- Debian (the next one)
- macOS 11.15

**Comment by wm1995** [comment]
Has this issue been resolved? I couldn't find this dependency listed anywhere in the documentation (which still states that OS X and Linux are both supported), and it took me a long while to diagnose the error as an out-of-date gcc compiler. Having both #479 and this issue closed seems a bit misleading.

**Comment by riddell-stan** [comment]
Thanks for posting. We do need to put this somewhere.

A quick fix would be to add an FAQ section with this information. We can add a link to it from PyStan's FAQ section as well.

**Comment by riddell-stan** [comment]
@wm1995 The docs now say that you need a (very) recent version of gcc or clang.

You may be able to get things working with any version of gcc or clang which Stan supports (see the CmdStan docs). You will have to build httpstan from scratch. You will not be able to use the PyPI wheels.

We don't test on platforms using older versions of gcc or clang. So I'm hesitant to put anything about this in the documentation. If you manage to get things working, posting a summary of your experience on the Stan Forums would be welcome.

**Comment by wm1995** [comment]
Thanks! I managed to get the PyPI wheel working by updating gcc, and haven't had an issue since, but I'll bear it in mind that that isn't officially supported. I've made [a post](https://discourse.mc-stan.org/t/pystan-3-gcc-compilers-and-docker-images/21342) to the Stan forums summarising my experience.

**Comment by riddell-stan** [comment]
I agree a warning message would be valuable.

Detecting a user's compiler is a bit of a challenge. One of the pybind11 example repos illustrates how to do it. The technique is not particularly easy to understand.

Let's see if people notice the C++ compiler requirement notices in the documentation. (I've also added them to the PyStan docs.)
