### ISSUE TITLE
CI: fail_fast

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/httpstan#502]
Do we want to use `fail_fast: false`, so each matrix item runs the process

https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

```
strategy:
    fail-fast: false
```

Currently, if there is some Linux error all jobs get canceled, which might not be optimal if there is different error on macOS

**Comment by riddell-stan** [comment]
The default `true` makes sense to me.

We don't allow code in this repository that causes *any* test failures. So failing all jobs if one fails seems fine to me. And it comes with the benefit of speeding up tests in general (by using fewer resources).
