### ISSUE TITLE
CI: Increase macOS testing

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/httpstan#503]
There is an option to use also 10.15 (Catalina) and 11.0 (Big Sur) images.

Not sure if these are needed if 10.14 is compatible with the newer images.

**Comment by riddell-stan** [comment]
`httpstan` is hyper-conservative about supporting new platforms/architectures. Or at least that has always been my intent. I think I gestured at this in one of the discourse posts. No new platforms/architectures/features until we have a track record of on-time releases.

I do think we need a "Supported Platforms" page in the pystan or httpstan documentation to make this crystal clear though.
