### ISSUE TITLE
curl sometimes fails to download Stan, Stan math tarballs

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#537]
```
downloading build/archives/math-v4.0.1.tar.gz
extracting archive build/archives/math-v4.0.1.tar.gz
tar -C build -zxf build/archives/math-v4.0.1.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make: *** [Makefile:75: build/math-4.0.1] Error 2
```

I think this came up before (somewhere). There must be some `curl` flag we can use to detect this problem and re-try the download.

**Comment by ahartikainen** [comment]
https://curl.se/docs/manpage.html

I think there are couple of options we can use

e.g

    --retry 5

**Comment by riddell-stan** [comment]
When I looked into this, one thing I remember learning is that ``--retry`` is subtly different than what one might expect. It doesn't retry on a wide range of errors (e.g., 404).

```
--retry <num>
       If a transient error is returned when curl tries  to  perform  a
       transfer,  it  will retry this number of times before giving up.
       Setting the number to 0 makes curl do no retries (which  is  the
       default).  Transient  error  means either: a timeout, an FTP 4xx
       response code or an HTTP 408 or 5xx response code.
```

I think we need to find out what is happening. What response code are we getting when we download an incomplete package?

**Comment by riddell-stan** [comment]
If updates to httpstan remain rare, this doesn't seem worth worrying about.
