### ISSUE TITLE
BrokenProcessPool when running in terminal

### ISSUE THREAD

**Issue by forsakendaemon** [stan-dev/httpstan#539]
Running httpstan in a terminal (and interfacing with it via python requests, I run into a recurrent BrokenProcessPool error. I originally thought that this was due to attempting to use Jupyter and PyStan3 (which is very broken), but this seems to have narrowed it down to httpstan itself.

In a terminal: `python -m httpstan`

And then in a python console:
```import requests
url = 'http://127.0.0.1:8080/v1'
obj = {'program_code' : "parameters {real y;} model {y ~ normal(0,1);}"}
x = requests.post(f"{url}/models", json = obj)
modelname = x.json()['name']
fit = requests.post(f"{url}/{modelname}/fits", json = {"function" : "stan::services::sample::hmc_nuts_diag_e_adapt", "chain" : 1, "num_samples" : 1000, "data" : data})
x = requests.get(f"{url}/{fit.json()['name']}")
x.text

'{"name": "operations/vlak2bzp", "metadata": {"fit": {"name": "models/7dw66bzi/fits/vlak2bzp"}}, "done": true, "result": {"message": "Exception during call to services function: 'BrokenProcessPool(\'A child process terminated abruptly, the process pool is not usable anymore\')', traceback: '[\'  File \\"/opt/conda/envs/g20.11/lib/python3.9/site-packages/httpstan/services_stub.py\\", line 101, in call\\\\n    future = asyncio.get_running_loop().run_in_executor(executor, lazy_function_wrapper_partial)  # type: ignore\\\\n\', \'  File \\"/opt/conda/envs/g20.11/lib/python3.9/asyncio/base_events.py\\", line 814, in run_in_executor\\\\n    executor.submit(func, *args), loop=self)\\\\n\', \'  File \\"/opt/conda/envs/g20.11/lib/python3.9/concurrent/futures/process.py\\", line 681, in submit\\\\n    raise BrokenProcessPool(self._broken)\\\\n\']'", "status": "Bad Request", "code": 400}}'
```

I'm working in a Docker image (based on `jupyter/datascience-notebook:latest`) and the only way I've managed to fix it is rebuilding the image from scratch, which isn't really ideal - restarting jupyter doesn't improve matters, and there's nothing running in the background that I can find. Plenty of memory is available to the container - it's using about 300MB and has about 4GB unused.

**Comment by riddell-stan** [comment]
Thanks for the report.

When you say "python console" you mean a Python or IPython console? Or is this a code block in Jupyter? Can you share the docker image you are using?

PyStan 3 doesn't work in Jupyter notebooks due to an asyncio bug in Jupyter, <https://github.com/jupyter/notebook/issues/3397>. This is a known issue. (We do need an FAQ entry about it in the PyStan docs.)

**Comment by forsakendaemon** [comment]
Sorry - it's an IPython console. I'm not running httpstan via Jupyter notebooks due to the asyncio issue. My thought was to run httpstan in a separate console within the container (so it's not running within the Jupyter event loop) and then interface with it manually. Eventually I'd like to refactor out the async stuff in PyStan3 so that it doesn't spin up httpstan internally and does the right things with `async`/`await` when it's already in an event loop, but I'm still coming to grips with how the code is organised.

I'm using https://hub.docker.com/r/jupyter/datascience-notebook/.

**Comment by riddell-stan** [comment]
What you're doing should work fine. Looks like the jupyter docker images are based on Ubuntu 20.04.

So are both commands being run inside the same docker container?

**Comment by forsakendaemon** [comment]
Yeah, that's what I thought.

Yes, both in the same container.

I'm having trouble recreating it now, I'm wondering whether something else went wrong earlier in the container that broke the ProcessPool, and hasn't happened again. I'll keep investigating and let you know if it breaks again. I'll be working on this pretty intensively for the next few days, so if I haven't updated by the end of the week feel free to close the ticket as not replicable.

**Comment by IvanUkhov** [comment]
Hello, I have recently rewritten the code to use PyStan 3, and now I am constantly running into `BrokenProcessPool` when running in a Docker container.

```
BrokenProcessPool('A child process terminated abruptly, the process pool is not usable anymore')`, traceback:
[
'  File "/usr/local/lib/python3.8/site-packages/httpstan/services_stub.py", line 112, in call\n    future = asyncio.get_running_loop().run_in_executor(executor, lazy_function_wrapper_partial)  # type: ignore\n',
'  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 783, in run_in_executor\n    executor.submit(func, *args), loop=self)\n',
'  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 629, in submit\n    raise BrokenProcessPool(self._broken)
]
```

Which is raised in

```
" File "/usr/local/lib/python3.8/site-packages/stan/model.py", line 231, in go "
```

Would appreciate any ideas! Thank you.

**Comment by forsakendaemon** [comment]
Hmmm, I wonder whether it's something about the container. What base image are you using? Maybe there's a shared dependency somewhere.

**Comment by IvanUkhov** [comment]
The base image is `python:3.8.9-slim`.
