### ISSUE TITLE
log_prob endpoint does not support nested parameters

### ISSUE THREAD

**Issue by dorranh** [stan-dev/httpstan#569]
Hi httpstan team! My colleagues and I are exploring using httpstan as a means of integrating an application we are developing with Stan and have run into a limitation of the `log_prob` endpoint. Specifically, it [looks like this endpoint](https://github.com/stan-dev/httpstan/blob/f32e8901fc50528aeb3008b482c3e1ce260314b2/httpstan/schemas.py#L195) only accepts an array of numerical parameter values while in Stan you can define parameters as vectors to avoid having to explicitly assign a name to each element. Is there a way to specify the inputs to `log_prob` in this case? I've included an example parameters section below.

```stan
parameters {
  vector[n] theta;
  real sigma;
}
```

**Comment by riddell-stan** [comment]
Thanks for the note. As this is a feature request, this is something you might want to post to the Stan discussion board. (We're trying to limit the issue tracker to bug requests.)

It might be useful to know that httpstan isn't making any choices here. It's just wrapping Stan.

httpstan's log_prob endpoint wraps a Stan C++ function by the same name which has the following signature:

```cpp
    inline T__ log_prob(std::vector<T__>& params_r, std::vector<int>& params_i, std::ostream* pstream = nullptr)
```
