### ISSUE TITLE
Build fails due to changes in dependencies

### ISSUE THREAD

**Issue by bedaro** [stan-dev/httpstan#570]
I was trying to build my own wheel of 4.5.0 for a Windows Subsystem for Linux instance and encountered a ModuleNotFoundError for setuptools, even though setuptools is installed. (see [pip3-output.txt](https://github.com/stan-dev/httpstan/files/6728854/pip3-output.txt))

After a few hours of looking into the problem, I think the issue is related to changes that have been made in recent versions of pip. Or maybe it's related to poetry, I'm not sure. In any case, it appears to be the same issue as in pendulum: https://github.com/sdispater/pendulum/issues/454, and because of that I am able to copy the fixes made to pyproject.toml and get it working. I will submit a pull request shortly.

**Comment by ahartikainen** [comment]
Hi,

do you follow the steps in https://github.com/stan-dev/httpstan/blob/main/.github/workflows/main.yml

**Comment by Kriti007** [comment]
Hi I am trying to build Pystan locally by cloning this repo? What steps should I follow?

**Comment by riddell-stan** [comment]
See "Installation from source" at https://httpstan.readthedocs.io/en/latest/installation.html

**Comment by riddell-stan** [comment]
Closing. Please post questions about installation in the Stan forums.
