### ISSUE TITLE
Updating asyncio use

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/httpstan#571]
I have been following discussion concerning `get_event_loop` calls and I think the asyncio developers don't recommend this approach.

https://docs.python.org/3/library/asyncio-eventloop.html

> Because this function has rather complex behavior (especially when custom event loop policies are in use), using the get_running_loop() function is preferred to get_event_loop() in coroutines and callbacks.

> Consider also using the asyncio.run() function instead of using lower level functions to manually create and close an event loop.

There is also a thread in Python discourse that has some idea of using asyncio tasks and then manually following them.

https://discuss.python.org/t/supporting-asyncio-get-event-loop-run-until-complete-in-repls/5573/3

> That being said, you could potentially use something with asyncio.create_task() (if it’s a coroutine function), store the task internally, and then await them all at the end of your program with asyncio.gather(*tasks) – this can be decent approach as long as you remember to keep track of the tasks and await them at the end; it also ensures that the tasks will be completed concurrently (assuming there’s not blocking code within the tasks themselves). If the user needs the result immediately, you can maybe have a block flag (defaults to false, preferably) that directly returns task.result() instead of waiting until it has a chance to execute or the end of the program. Or, simply return the task object back to the user and let them handle it (be sure to include a link to the asyncio.Task docs with this approach).

**Comment by riddell-stan** [comment]
What's the issue? We do not use `get_event_loop`, following the recommendation.

**Comment by ahartikainen** [comment]
Yes, I'm living in the past, we have fixed this already. So sorry :D
