### ISSUE TITLE
distutils is deprecated as of Python 3.10

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#573]
distutils is deprecated, per [PEP 632](https://www.python.org/dev/peps/pep-0632/#migration-advice). httpstan should stop using it.

I think this should be easy. I believe setuptools provides the functions/classes from distutils we currently use.

Looks like distutils will be removed in Python 3.12.

(note: setuptools version 48 and higher contains a copy of distutils.)

**Comment by riddell-stan** [comment]
Ubuntu 20.04 does *not* ship with setuptools version 48 or higher (it ships with setuptools 45). Addressing this could safely wait until the release for Python 3.12.

**Comment by riddell-stan** [comment]
FYI: release date for 3.12 is: ``3.12.0 final: Monday, 2023-10-02``

**Comment by OriolAbril** [comment]
An issue related to this seems to be appearing on ArviZ CI even though it uses Python 3.9: https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=5902&view=logs&j=7f538728-4589-5563-0e87-d0823eb40420&t=ca181c57-2f6c-5cc2-019c-e7792481591d&l=81. Any ideas why or potential workarounds?

**Comment by riddell-stan** [comment]
Not sure. I doubt it's related. "msvccompiler" suggests something related to Windows. Windows is not supported by httpstan.

**Comment by riddell-stan** [comment]
Upon reflection, this can be fixed today. There are no problems for Ubuntu 20.04. Remember to add `setuptools>=48` to the list of runtime requirements.
