### ISSUE TITLE
No matching distribution found for httpstan==4.5.0

### ISSUE THREAD

**Issue by michaelnlindsay** [stan-dev/httpstan#574]
Down a rabbit hole with dependency resolution.  Initial error tells me: `ERROR: Could not find a version that satisfies the requirement httpstan<4.6,>=4.5`

But when I attempt to install 4.5.0, I get `ERROR: No matching distribution found for httpstan==4.5.0 (from -r requirements.txt (line 27))`

Are there repo settings I can update to get this?

**Comment by ahartikainen** [comment]
What python do you use? What is your os?

**Comment by michaelnlindsay** [comment]
Sorry, that would have been helpful:
Vagrant (2.2.18) -> Virtualbox (6.1.26) -> Ubuntu Bionic (18.04)
Python 3.7 (venv)

**Comment by riddell-stan** [comment]
You cannot `pip install` the wheel on Ubuntu 18.04. Try Ubuntu 20.04. 

Installation from source should work on Ubuntu 18.04. Instructions are here: https://httpstan.readthedocs.io/en/latest/installation.html

**Comment by michaelnlindsay** [comment]
Hi!  Thanks for that.  I'm actually having a bit of trouble following those commands.  What I've done instead is:
1) git clone git@github.com:stan-dev/httpstan.git
2) run make out of there
3) ?? run python3 build.py

build.py exits 0, but doesn't output anything and I'm not sure what to do next.  Sorry for my noobishness.

**Comment by michaelnlindsay** [comment]
Just now realizing `poetry` may be pseudo code for “the package in which this statement appears in the readme”.  Sorry, slow to catch up.  I'm making progress now, I'm sure I'll make quick work of this `importlib.resources` weirdness:

```
test (etl) vagrant@etl:/vagrant/tmp/httpstan$ python3 -m pip install importlib.resources
Collecting importlib.resources
  Downloading https://files.pythonhosted.org/packages/f2/6c/2f3b930513bb971172ffceb63cf4e910944e57451724e69b1dec97cfefa6/importlib_resources-5.2.2-py3-none-any.whl
Collecting zipp>=3.1.0; python_version < "3.10" (from importlib.resources)
  Downloading https://files.pythonhosted.org/packages/92/d9/89f433969fb8dc5b9cbdd4b4deb587720ec1aeb59a020cf15002b9593eef/zipp-3.5.0-py3-none-any.whl
Installing collected packages: zipp, importlib.resources
Successfully installed importlib.resources zipp-3.5.0
test (etl) vagrant@etl:/vagrant/tmp/httpstan$ python3 -m httpstan build
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/vagrant/tmp/httpstan/httpstan/__main__.py", line 10, in <module>
    import httpstan.app
  File "/vagrant/tmp/httpstan/httpstan/app.py", line 10, in <module>
    import httpstan.routes
  File "/vagrant/tmp/httpstan/httpstan/routes.py", line 7, in <module>
    import httpstan.views as views
  File "/vagrant/tmp/httpstan/httpstan/views.py", line 20, in <module>
    import httpstan.models
  File "/vagrant/tmp/httpstan/httpstan/models.py", line 11, in <module>
    import importlib.resources
ModuleNotFoundError: No module named 'importlib.resources'
```

**Comment by ahartikainen** [comment]
poetry is not pseudocode.

**Comment by michaelnlindsay** [comment]
Hi, thank you very much for walking me through this, I really appreciate it.

All of those steps I've now performed successfully except the last, installing the wheel, which reports:
`ERROR: httpstan-4.5.0-cp37-cp37m-manylinux_2_27_x86_64.whl is not a supported wheel on this platform.`
Any recommendations for how to address that?

**Comment by ahartikainen** [comment]
I think you need to update your pip

    python3 -m pip install pip -U

**Comment by michaelnlindsay** [comment]
That totally worked, all dependencies nicely tucked in now.  Thanks so much for all your help.

**Comment by michaelnlindsay** [comment]
Resolved
