### ISSUE TITLE
.tar.gz files not published to pypi for releases > 0.10.1

### ISSUE THREAD

**Issue by lazcamus** [stan-dev/httpstan#599]
I'm attempting to run prophet on an arm64 linux. It depends on pystan which depends on httpstan, which fetches httpstan 0.10.1 as the latest because that's the highest version .tar.gz that's available at https://pypi.org/simple/httpstan/ 

I'd appreciate it if whomever has write access to pypi could upload modern source .tar.gz files so pip will attempt a source install.

**Comment by riddell-stan** [comment]
Sounds like you might be looking for PyStan 2? No version of PyStan 3 should be asking for httpstan 0.10.1.

httpstan is only available as a wheel at the moment.

As this isn't a bug or a confirmed feature, I'll close this. Feel free to post questions or feature requests on the Stan Forums.

**Comment by lazcamus** [comment]
> httpstan is only available as a wheel at the moment.

Right. And this is why I can't `pip3 install httpstan` on linux-arm64 (or darwin arm either) because there are no wheels built for it. `pip` attempts to grab the latest source `.tar.gz`:

```
% pip3 install httpstan
Collecting httpstan
  Downloading httpstan-0.10.1.tar.gz (16.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 40.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
```

If you want to allow `pip` to install a modern version of `httpstan` on these platforms, you can either pre-build a wheel for each one, or publish the source `.tar.gz` to pypi like was done with version `0.10.1`

**Comment by ahartikainen** [comment]
I'm not sure if pip can even install httpstan from tar.gz.

**Comment by riddell-stan** [comment]
@lazcamus You're absolutely right about this being an issue. I've removed the source distributions from PyPI, seeing that you cannot pip install them. You shouldn't get the error now.

We do want to release aarch64 / arm wheels. We currently lack the expertise to update the wheel building system we have (stan-dev/httpstan-wheels).
