### ISSUE TITLE
Serializing draws and sending them via HTTP is currently slow

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#60]
httpstan is slow for the simple case of sampling from simple models with high ``num_samples`` count. Playing around with things suggests the bottleneck is serialization into JSON and single-thread transmission via HTTP (aiohttp does this). Additional profiling is needed.

For the very important case of sampling from a complex model where fitting the model takes minutes or hours, httpstan works fine.

**Comment by bob-carpenter** [comment]
Not surprising.  Even serialization to ASCII is slow compared to just streaming binary bytes.  

How bad is the slowdown?

The only real problem with this is probably when people compare Stan to other systems on very simple models.  Of course, our compilation time is so bad that if they did that and included compilation, it wouldn't matter anyway.

**Comment by riddell-stan** [comment]
Right now the slowdown is very bad. I need to profile it a bit to make sure it's the serialization and not the single-threaded HTTP server. I am using a maximally verbose serialization scheme. Switching over to protocol buffers might fix some problems.

**Comment by riddell-stan** [comment]
Some things to try out:
- Send the output from Stan C++ in batches
- Try uvloop instead of CPython's default https://github.com/MagicStack/uvloop

**Comment by riddell-stan** [comment]
uvloop seems to have improved things. httpstan is certainly usable right now.
