### ISSUE TITLE
How to install httpstan on mac M1 system?

### ISSUE THREAD

**Issue by navjotkaur7** [stan-dev/httpstan#628]
On using `python3 -m pip install httpstan`
I get the following error:
```
ERROR: Could not find a version that satisfies the requirement httpstan (from versions: none)
ERROR: No matching distribution found for httpstan
```

I also tried install the *.whl, but they do not seem to be supported on the platform. 
Could you suggest how to install?

Python version: 3.8. (Also tried with Python 3.9, doesn't help).
I updated the pip using `pip install -U pip` and the current version is 22.3.1

**Comment by riddell-stan** [comment]
Users with an M1 chip need to install from source. It's not too difficult. Instructions are in the documentation: https://httpstan.readthedocs.io/en/latest/installation.html
