### ISSUE TITLE
support windows

### ISSUE THREAD

**Issue by shadowcrow0** [stan-dev/httpstan#632]
I am user for windows. We run experiment on windows platform in school. The school prefers windows system.Our experiment rely on pystan. we need to install virtual machine build the experiment on linux. Is it possible to have a windows version?

**Comment by bob-carpenter** [comment]
You might consider running cmdstanpy, which is easier to get running under Windows because it cuts out a binary dependency.  It doesn't have all the functionality of pystan3 for things like evaluating log densities or performing transforms, but if you only want to fit models, it should be fine.

**Comment by riddell-stan** [comment]
This is addressed in the PyStan FAQ: https://pystan.readthedocs.io/en/latest/faq.html#is-windows-supported

> Is Windows supported?[¶](https://pystan.readthedocs.io/en/latest/faq.html#is-windows-supported)
> If [WSL2](https://docs.microsoft.com/en-us/windows/wsl/) works for you, then the answer is “yes,” otherwise the answer is “no.”
> Experience has proven that supporting PyStan on Windows is challenging and requires a considerable investment of resources. If you would like to fund the development and ongoing maintenance of a version of PyStan which works on Windows, please post your proposal for discussion on the [Stan forum](https://discourse.mc-stan.org/).
