### ISSUE TITLE
Unable to find installation candidates for httpstan

### ISSUE THREAD

**Issue by scholarazwa** [stan-dev/httpstan#639]
Hi. I am trying to install pystan via poetry and it always get stuck at installing httpstan, no matter what the version is.

Here what I did:
poetry add pystan="3.5.0" -> Installing httpstan (4.8.2): Failed
poetry add pystan="3.6.0" -> Installing httpstan (4.9.1): Failed
poetry add pystan="3.7.0" -> Installing httpstan (4.10.1): Failed

The error says "Unable to find installation candidates for httpstan (4.x.x)"

Can someone help me on how to resolve this? Thank you.

Btw, I am on an M2 Apple Silicon Macbook Air.

**Comment by riddell-stan** [comment]
Thanks to the work of @mikediessner we now have an FAQ item for this: https://pystan.readthedocs.io/en/latest/faq.html#how-can-i-run-pystan-on-macos-with-apple-silicon-chips-apple-m1-m2-etc

**Comment by scholarazwa** [comment]
Thanks. Let me try that and report back.

**Comment by scholarazwa** [comment]
I have tried the suggested solution and it works. Just a few notes for others in the future:
- If you already have poetry installed you can skip the 'python3 -m pip install poetry' and 'python3 -m poetry build' step.
- Instead, just do 'poetry init' to initialize the httpstan folder with poetry.
- Then, simply run 'poetry build'.
- The output will be two files: a '.tar.gz' and a '.whl' in the dist folder.

Next, to install httpstan into an existing project, just copy the output files above into your project folder , then do:
- pip install *.whl
- After that, install pystan via 'pip install pystan --no-binary pystan'
- Now you have both httpstan and pystan installed.

In my case, I needed the above packages in order to make Prophet work. So now I can simply do:
- 'poetry add prophet'
- And my environment is now setup correctly.
